# coding: utf-8

"""
    NRF NFDiscovery Service

    NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0.alpha-4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.ipv4_address_range import Ipv4AddressRange  # noqa: E501
from openapi_client.rest import ApiException

class TestIpv4AddressRange(unittest.TestCase):
    """Ipv4AddressRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Ipv4AddressRange
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.ipv4_address_range.Ipv4AddressRange()  # noqa: E501
        if include_optional :
            return Ipv4AddressRange(
                start = '198.51.100.1', 
                end = '198.51.100.1'
            )
        else :
            return Ipv4AddressRange(
        )

    def testIpv4AddressRange(self):
        """Test Ipv4AddressRange"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
