# coding: utf-8

"""
    N32 Handshake API

    N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0.alpha-3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.com.h21lab.TS29573_N32_Handshake.handler.api_ie_mapping import ApiIeMapping  # noqa: E501
from openapi_client.rest import ApiException

class TestApiIeMapping(unittest.TestCase):
    """ApiIeMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiIeMapping
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.api_ie_mapping.ApiIeMapping()  # noqa: E501
        if include_optional :
            return ApiIeMapping(
                api_signature = null, 
                api_method = null, 
                ie_list = [
                    openapi_client.models.ie_info.IeInfo(
                        ie_loc = null, 
                        ie_type = null, 
                        req_ie = '0', 
                        rsp_ie = '0', 
                        is_modifiable = True, )
                    ]
            )
        else :
            return ApiIeMapping(
                api_signature = null,
                api_method = null,
                ie_list = [
                    openapi_client.models.ie_info.IeInfo(
                        ie_loc = null, 
                        ie_type = null, 
                        req_ie = '0', 
                        rsp_ie = '0', 
                        is_modifiable = True, )
                    ],
        )

    def testApiIeMapping(self):
        """Test ApiIeMapping"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
