# coding: utf-8

"""
    NRF NFDiscovery Service

    NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0.alpha-4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.lmf_info import LmfInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestLmfInfo(unittest.TestCase):
    """LmfInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LmfInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.lmf_info.LmfInfo()  # noqa: E501
        if include_optional :
            return LmfInfo(
                serving_client_types = [
                    null
                    ], 
                lmf_id = '0', 
                serving_access_types = [
                    '3GPP_ACCESS'
                    ], 
                serving_an_node_types = [
                    null
                    ], 
                serving_rat_types = [
                    null
                    ]
            )
        else :
            return LmfInfo(
        )

    def testLmfInfo(self):
        """Test LmfInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
