# coding: utf-8

"""
    N32 Handshake API

    N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0.alpha-3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from com.h21lab.TS29573_N32_Handshake.model.n32_f_error_report_api import N32FErrorReportApi  # noqa: E501
from openapi_client.rest import ApiException


class TestN32FErrorReportApi(unittest.TestCase):
    """N32FErrorReportApi unit test stubs"""

    def setUp(self):
        self.api = com.h21lab.TS29573_N32_Handshake.model.n32_f_error_report_api.N32FErrorReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_n32f_error(self):
        """Test case for post_n32f_error

        N32-f Error Reporting Procedure  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
