# coding: utf-8

"""
    N32 Handshake API

    N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0.alpha-3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.com.h21lab.TS29573_N32_Handshake.handler.sec_param_exch_rsp_data import SecParamExchRspData  # noqa: E501
from openapi_client.rest import ApiException

class TestSecParamExchRspData(unittest.TestCase):
    """SecParamExchRspData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SecParamExchRspData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.sec_param_exch_rsp_data.SecParamExchRspData()  # noqa: E501
        if include_optional :
            return SecParamExchRspData(
                n32f_context_id = 'a', 
                selected_jwe_cipher_suite = '0', 
                selected_jws_cipher_suite = '0', 
                sel_protection_policy_info = openapi_client.models.protection_policy.ProtectionPolicy(
                    api_ie_mapping_list = [
                        openapi_client.models.api_ie_mapping.ApiIeMapping(
                            api_signature = null, 
                            api_method = null, 
                            ie_list = [
                                openapi_client.models.ie_info.IeInfo(
                                    ie_loc = null, 
                                    ie_type = null, 
                                    req_ie = '0', 
                                    rsp_ie = '0', 
                                    is_modifiable = True, )
                                ], )
                        ], 
                    data_type_enc_policy = [
                        null
                        ], ), 
                ipx_provider_sec_info_list = [
                    openapi_client.models.ipx_provider_sec_info.IpxProviderSecInfo(
                        ipx_provider_id = '0', 
                        raw_public_key_list = [
                            '0'
                            ], 
                        certificate_list = [
                            '0'
                            ], )
                    ], 
                sender = '0'
            )
        else :
            return SecParamExchRspData(
                n32f_context_id = 'a',
        )

    def testSecParamExchRspData(self):
        """Test SecParamExchRspData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
