# coding: utf-8

"""
    N32 Handshake API

    N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0.alpha-3
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class N32fErrorDetail(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'attribute': 'str',
        'msg_reconstruct_fail_reason': 'FailureReason'
    }

    attribute_map = {
        'attribute': 'attribute',
        'msg_reconstruct_fail_reason': 'msgReconstructFailReason'
    }

    def __init__(self, attribute=None, msg_reconstruct_fail_reason=None, local_vars_configuration=None):  # noqa: E501
        """N32fErrorDetail - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._attribute = None
        self._msg_reconstruct_fail_reason = None
        self.discriminator = None

        self.attribute = attribute
        self.msg_reconstruct_fail_reason = msg_reconstruct_fail_reason

    @property
    def attribute(self):
        """Gets the attribute of this N32fErrorDetail.  # noqa: E501


        :return: The attribute of this N32fErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._attribute

    @attribute.setter
    def attribute(self, attribute):
        """Sets the attribute of this N32fErrorDetail.


        :param attribute: The attribute of this N32fErrorDetail.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and attribute is None:  # noqa: E501
            raise ValueError("Invalid value for `attribute`, must not be `None`")  # noqa: E501

        self._attribute = attribute

    @property
    def msg_reconstruct_fail_reason(self):
        """Gets the msg_reconstruct_fail_reason of this N32fErrorDetail.  # noqa: E501


        :return: The msg_reconstruct_fail_reason of this N32fErrorDetail.  # noqa: E501
        :rtype: FailureReason
        """
        return self._msg_reconstruct_fail_reason

    @msg_reconstruct_fail_reason.setter
    def msg_reconstruct_fail_reason(self, msg_reconstruct_fail_reason):
        """Sets the msg_reconstruct_fail_reason of this N32fErrorDetail.


        :param msg_reconstruct_fail_reason: The msg_reconstruct_fail_reason of this N32fErrorDetail.  # noqa: E501
        :type: FailureReason
        """
        if self.local_vars_configuration.client_side_validation and msg_reconstruct_fail_reason is None:  # noqa: E501
            raise ValueError("Invalid value for `msg_reconstruct_fail_reason`, must not be `None`")  # noqa: E501

        self._msg_reconstruct_fail_reason = msg_reconstruct_fail_reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, N32fErrorDetail):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, N32fErrorDetail):
            return True

        return self.to_dict() != other.to_dict()
