# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.base_model_ import Model
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.identity_range import IdentityRange
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.plmn_range import PlmnRange
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.supi_range import SupiRange
from openapi_server import util

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.identity_range import IdentityRange  # noqa: E501
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.plmn_range import PlmnRange  # noqa: E501
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.supi_range import SupiRange  # noqa: E501

class ChfInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, supi_range_list=None, gpsi_range_list=None, plmn_range_list=None, group_id=None):  # noqa: E501
        """ChfInfo - a model defined in OpenAPI

        :param supi_range_list: The supi_range_list of this ChfInfo.  # noqa: E501
        :type supi_range_list: List[SupiRange]
        :param gpsi_range_list: The gpsi_range_list of this ChfInfo.  # noqa: E501
        :type gpsi_range_list: List[IdentityRange]
        :param plmn_range_list: The plmn_range_list of this ChfInfo.  # noqa: E501
        :type plmn_range_list: List[PlmnRange]
        :param group_id: The group_id of this ChfInfo.  # noqa: E501
        :type group_id: str
        """
        self.openapi_types = {
            'supi_range_list': List[SupiRange],
            'gpsi_range_list': List[IdentityRange],
            'plmn_range_list': List[PlmnRange],
            'group_id': str
        }

        self.attribute_map = {
            'supi_range_list': 'supiRangeList',
            'gpsi_range_list': 'gpsiRangeList',
            'plmn_range_list': 'plmnRangeList',
            'group_id': 'groupId'
        }

        self._supi_range_list = supi_range_list
        self._gpsi_range_list = gpsi_range_list
        self._plmn_range_list = plmn_range_list
        self._group_id = group_id

    @classmethod
    def from_dict(cls, dikt) -> 'ChfInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChfInfo of this ChfInfo.  # noqa: E501
        :rtype: ChfInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def supi_range_list(self):
        """Gets the supi_range_list of this ChfInfo.


        :return: The supi_range_list of this ChfInfo.
        :rtype: List[SupiRange]
        """
        return self._supi_range_list

    @supi_range_list.setter
    def supi_range_list(self, supi_range_list):
        """Sets the supi_range_list of this ChfInfo.


        :param supi_range_list: The supi_range_list of this ChfInfo.
        :type supi_range_list: List[SupiRange]
        """

        self._supi_range_list = supi_range_list

    @property
    def gpsi_range_list(self):
        """Gets the gpsi_range_list of this ChfInfo.


        :return: The gpsi_range_list of this ChfInfo.
        :rtype: List[IdentityRange]
        """
        return self._gpsi_range_list

    @gpsi_range_list.setter
    def gpsi_range_list(self, gpsi_range_list):
        """Sets the gpsi_range_list of this ChfInfo.


        :param gpsi_range_list: The gpsi_range_list of this ChfInfo.
        :type gpsi_range_list: List[IdentityRange]
        """

        self._gpsi_range_list = gpsi_range_list

    @property
    def plmn_range_list(self):
        """Gets the plmn_range_list of this ChfInfo.


        :return: The plmn_range_list of this ChfInfo.
        :rtype: List[PlmnRange]
        """
        return self._plmn_range_list

    @plmn_range_list.setter
    def plmn_range_list(self, plmn_range_list):
        """Sets the plmn_range_list of this ChfInfo.


        :param plmn_range_list: The plmn_range_list of this ChfInfo.
        :type plmn_range_list: List[PlmnRange]
        """

        self._plmn_range_list = plmn_range_list

    @property
    def group_id(self):
        """Gets the group_id of this ChfInfo.


        :return: The group_id of this ChfInfo.
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this ChfInfo.


        :param group_id: The group_id of this ChfInfo.
        :type group_id: str
        """

        self._group_id = group_id
