# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.base_model_ import Model
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.atom import Atom
from openapi_server import util

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.atom import Atom  # noqa: E501

class DnfUnit(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dnf_unit=None):  # noqa: E501
        """DnfUnit - a model defined in OpenAPI

        :param dnf_unit: The dnf_unit of this DnfUnit.  # noqa: E501
        :type dnf_unit: List[Atom]
        """
        self.openapi_types = {
            'dnf_unit': List[Atom]
        }

        self.attribute_map = {
            'dnf_unit': 'dnfUnit'
        }

        self._dnf_unit = dnf_unit

    @classmethod
    def from_dict(cls, dikt) -> 'DnfUnit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DnfUnit of this DnfUnit.  # noqa: E501
        :rtype: DnfUnit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dnf_unit(self):
        """Gets the dnf_unit of this DnfUnit.


        :return: The dnf_unit of this DnfUnit.
        :rtype: List[Atom]
        """
        return self._dnf_unit

    @dnf_unit.setter
    def dnf_unit(self, dnf_unit):
        """Sets the dnf_unit of this DnfUnit.


        :param dnf_unit: The dnf_unit of this DnfUnit.
        :type dnf_unit: List[Atom]
        """
        if dnf_unit is None:
            raise ValueError("Invalid value for `dnf_unit`, must not be `None`")  # noqa: E501

        self._dnf_unit = dnf_unit
