# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.base_model_ import Model
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.access_type import AccessType
from openapi_server import util

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.access_type import AccessType  # noqa: E501

class PcscfInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, access_type=None, dnn_list=None):  # noqa: E501
        """PcscfInfo - a model defined in OpenAPI

        :param access_type: The access_type of this PcscfInfo.  # noqa: E501
        :type access_type: List[AccessType]
        :param dnn_list: The dnn_list of this PcscfInfo.  # noqa: E501
        :type dnn_list: List[str]
        """
        self.openapi_types = {
            'access_type': List[AccessType],
            'dnn_list': List[str]
        }

        self.attribute_map = {
            'access_type': 'accessType',
            'dnn_list': 'dnnList'
        }

        self._access_type = access_type
        self._dnn_list = dnn_list

    @classmethod
    def from_dict(cls, dikt) -> 'PcscfInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PcscfInfo of this PcscfInfo.  # noqa: E501
        :rtype: PcscfInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_type(self):
        """Gets the access_type of this PcscfInfo.


        :return: The access_type of this PcscfInfo.
        :rtype: List[AccessType]
        """
        return self._access_type

    @access_type.setter
    def access_type(self, access_type):
        """Sets the access_type of this PcscfInfo.


        :param access_type: The access_type of this PcscfInfo.
        :type access_type: List[AccessType]
        """

        self._access_type = access_type

    @property
    def dnn_list(self):
        """Gets the dnn_list of this PcscfInfo.


        :return: The dnn_list of this PcscfInfo.
        :rtype: List[str]
        """
        return self._dnn_list

    @dnn_list.setter
    def dnn_list(self, dnn_list):
        """Sets the dnn_list of this PcscfInfo.


        :param dnn_list: The dnn_list of this PcscfInfo.
        :type dnn_list: List[str]
        """

        self._dnn_list = dnn_list
