# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.base_model_ import Model
from openapi_server import util


class PfdData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, app_ids=None, af_ids=None):  # noqa: E501
        """PfdData - a model defined in OpenAPI

        :param app_ids: The app_ids of this PfdData.  # noqa: E501
        :type app_ids: List[str]
        :param af_ids: The af_ids of this PfdData.  # noqa: E501
        :type af_ids: List[str]
        """
        self.openapi_types = {
            'app_ids': List[str],
            'af_ids': List[str]
        }

        self.attribute_map = {
            'app_ids': 'appIds',
            'af_ids': 'afIds'
        }

        self._app_ids = app_ids
        self._af_ids = af_ids

    @classmethod
    def from_dict(cls, dikt) -> 'PfdData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PfdData of this PfdData.  # noqa: E501
        :rtype: PfdData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_ids(self):
        """Gets the app_ids of this PfdData.


        :return: The app_ids of this PfdData.
        :rtype: List[str]
        """
        return self._app_ids

    @app_ids.setter
    def app_ids(self, app_ids):
        """Sets the app_ids of this PfdData.


        :param app_ids: The app_ids of this PfdData.
        :type app_ids: List[str]
        """

        self._app_ids = app_ids

    @property
    def af_ids(self):
        """Gets the af_ids of this PfdData.


        :return: The af_ids of this PfdData.
        :rtype: List[str]
        """
        return self._af_ids

    @af_ids.setter
    def af_ids(self, af_ids):
        """Sets the af_ids of this PfdData.


        :param af_ids: The af_ids of this PfdData.
        :type af_ids: List[str]
        """

        self._af_ids = af_ids
