# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.base_model_ import Model
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.plmn_id import PlmnId
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.snssai import Snssai
import re
from openapi_server import util

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.plmn_id import PlmnId  # noqa: E501
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.snssai import Snssai  # noqa: E501
import re  # noqa: E501

class PlmnSnssai(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, plmn_id=None, s_nssai_list=None, nid=None):  # noqa: E501
        """PlmnSnssai - a model defined in OpenAPI

        :param plmn_id: The plmn_id of this PlmnSnssai.  # noqa: E501
        :type plmn_id: PlmnId
        :param s_nssai_list: The s_nssai_list of this PlmnSnssai.  # noqa: E501
        :type s_nssai_list: List[Snssai]
        :param nid: The nid of this PlmnSnssai.  # noqa: E501
        :type nid: str
        """
        self.openapi_types = {
            'plmn_id': PlmnId,
            's_nssai_list': List[Snssai],
            'nid': str
        }

        self.attribute_map = {
            'plmn_id': 'plmnId',
            's_nssai_list': 'sNssaiList',
            'nid': 'nid'
        }

        self._plmn_id = plmn_id
        self._s_nssai_list = s_nssai_list
        self._nid = nid

    @classmethod
    def from_dict(cls, dikt) -> 'PlmnSnssai':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlmnSnssai of this PlmnSnssai.  # noqa: E501
        :rtype: PlmnSnssai
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plmn_id(self):
        """Gets the plmn_id of this PlmnSnssai.


        :return: The plmn_id of this PlmnSnssai.
        :rtype: PlmnId
        """
        return self._plmn_id

    @plmn_id.setter
    def plmn_id(self, plmn_id):
        """Sets the plmn_id of this PlmnSnssai.


        :param plmn_id: The plmn_id of this PlmnSnssai.
        :type plmn_id: PlmnId
        """
        if plmn_id is None:
            raise ValueError("Invalid value for `plmn_id`, must not be `None`")  # noqa: E501

        self._plmn_id = plmn_id

    @property
    def s_nssai_list(self):
        """Gets the s_nssai_list of this PlmnSnssai.


        :return: The s_nssai_list of this PlmnSnssai.
        :rtype: List[Snssai]
        """
        return self._s_nssai_list

    @s_nssai_list.setter
    def s_nssai_list(self, s_nssai_list):
        """Sets the s_nssai_list of this PlmnSnssai.


        :param s_nssai_list: The s_nssai_list of this PlmnSnssai.
        :type s_nssai_list: List[Snssai]
        """
        if s_nssai_list is None:
            raise ValueError("Invalid value for `s_nssai_list`, must not be `None`")  # noqa: E501

        self._s_nssai_list = s_nssai_list

    @property
    def nid(self):
        """Gets the nid of this PlmnSnssai.


        :return: The nid of this PlmnSnssai.
        :rtype: str
        """
        return self._nid

    @nid.setter
    def nid(self, nid):
        """Sets the nid of this PlmnSnssai.


        :param nid: The nid of this PlmnSnssai.
        :type nid: str
        """
        if nid is not None and not re.search(r'^[A-Fa-f0-9]{11}$', nid):  # noqa: E501
            raise ValueError("Invalid value for `nid`, must be a follow pattern or equal to `/^[A-Fa-f0-9]{11}$/`")  # noqa: E501

        self._nid = nid
