# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.base_model_ import Model
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.dnn_upf_info_item import DnnUpfInfoItem
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.snssai import Snssai
from openapi_server import util

from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.dnn_upf_info_item import DnnUpfInfoItem  # noqa: E501
from openapi_server.com.h21lab.TS29510_Nnrf_NFDiscovery.handler.snssai import Snssai  # noqa: E501

class SnssaiUpfInfoItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, s_nssai=None, dnn_upf_info_list=None, redundant_transport=False):  # noqa: E501
        """SnssaiUpfInfoItem - a model defined in OpenAPI

        :param s_nssai: The s_nssai of this SnssaiUpfInfoItem.  # noqa: E501
        :type s_nssai: Snssai
        :param dnn_upf_info_list: The dnn_upf_info_list of this SnssaiUpfInfoItem.  # noqa: E501
        :type dnn_upf_info_list: List[DnnUpfInfoItem]
        :param redundant_transport: The redundant_transport of this SnssaiUpfInfoItem.  # noqa: E501
        :type redundant_transport: bool
        """
        self.openapi_types = {
            's_nssai': Snssai,
            'dnn_upf_info_list': List[DnnUpfInfoItem],
            'redundant_transport': bool
        }

        self.attribute_map = {
            's_nssai': 'sNssai',
            'dnn_upf_info_list': 'dnnUpfInfoList',
            'redundant_transport': 'redundantTransport'
        }

        self._s_nssai = s_nssai
        self._dnn_upf_info_list = dnn_upf_info_list
        self._redundant_transport = redundant_transport

    @classmethod
    def from_dict(cls, dikt) -> 'SnssaiUpfInfoItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SnssaiUpfInfoItem of this SnssaiUpfInfoItem.  # noqa: E501
        :rtype: SnssaiUpfInfoItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def s_nssai(self):
        """Gets the s_nssai of this SnssaiUpfInfoItem.


        :return: The s_nssai of this SnssaiUpfInfoItem.
        :rtype: Snssai
        """
        return self._s_nssai

    @s_nssai.setter
    def s_nssai(self, s_nssai):
        """Sets the s_nssai of this SnssaiUpfInfoItem.


        :param s_nssai: The s_nssai of this SnssaiUpfInfoItem.
        :type s_nssai: Snssai
        """
        if s_nssai is None:
            raise ValueError("Invalid value for `s_nssai`, must not be `None`")  # noqa: E501

        self._s_nssai = s_nssai

    @property
    def dnn_upf_info_list(self):
        """Gets the dnn_upf_info_list of this SnssaiUpfInfoItem.


        :return: The dnn_upf_info_list of this SnssaiUpfInfoItem.
        :rtype: List[DnnUpfInfoItem]
        """
        return self._dnn_upf_info_list

    @dnn_upf_info_list.setter
    def dnn_upf_info_list(self, dnn_upf_info_list):
        """Sets the dnn_upf_info_list of this SnssaiUpfInfoItem.


        :param dnn_upf_info_list: The dnn_upf_info_list of this SnssaiUpfInfoItem.
        :type dnn_upf_info_list: List[DnnUpfInfoItem]
        """
        if dnn_upf_info_list is None:
            raise ValueError("Invalid value for `dnn_upf_info_list`, must not be `None`")  # noqa: E501

        self._dnn_upf_info_list = dnn_upf_info_list

    @property
    def redundant_transport(self):
        """Gets the redundant_transport of this SnssaiUpfInfoItem.


        :return: The redundant_transport of this SnssaiUpfInfoItem.
        :rtype: bool
        """
        return self._redundant_transport

    @redundant_transport.setter
    def redundant_transport(self, redundant_transport):
        """Sets the redundant_transport of this SnssaiUpfInfoItem.


        :param redundant_transport: The redundant_transport of this SnssaiUpfInfoItem.
        :type redundant_transport: bool
        """

        self._redundant_transport = redundant_transport
