# coding: utf-8

"""
    NRF NFDiscovery Service

    NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0.alpha-4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class BsfInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'dnn_list': 'list[str]',
        'ip_domain_list': 'list[str]',
        'ipv4_address_ranges': 'list[Ipv4AddressRange]',
        'ipv6_prefix_ranges': 'list[Ipv6PrefixRange]'
    }

    attribute_map = {
        'dnn_list': 'dnnList',
        'ip_domain_list': 'ipDomainList',
        'ipv4_address_ranges': 'ipv4AddressRanges',
        'ipv6_prefix_ranges': 'ipv6PrefixRanges'
    }

    def __init__(self, dnn_list=None, ip_domain_list=None, ipv4_address_ranges=None, ipv6_prefix_ranges=None, local_vars_configuration=None):  # noqa: E501
        """BsfInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._dnn_list = None
        self._ip_domain_list = None
        self._ipv4_address_ranges = None
        self._ipv6_prefix_ranges = None
        self.discriminator = None

        if dnn_list is not None:
            self.dnn_list = dnn_list
        if ip_domain_list is not None:
            self.ip_domain_list = ip_domain_list
        if ipv4_address_ranges is not None:
            self.ipv4_address_ranges = ipv4_address_ranges
        if ipv6_prefix_ranges is not None:
            self.ipv6_prefix_ranges = ipv6_prefix_ranges

    @property
    def dnn_list(self):
        """Gets the dnn_list of this BsfInfo.  # noqa: E501


        :return: The dnn_list of this BsfInfo.  # noqa: E501
        :rtype: list[str]
        """
        return self._dnn_list

    @dnn_list.setter
    def dnn_list(self, dnn_list):
        """Sets the dnn_list of this BsfInfo.


        :param dnn_list: The dnn_list of this BsfInfo.  # noqa: E501
        :type: list[str]
        """

        self._dnn_list = dnn_list

    @property
    def ip_domain_list(self):
        """Gets the ip_domain_list of this BsfInfo.  # noqa: E501


        :return: The ip_domain_list of this BsfInfo.  # noqa: E501
        :rtype: list[str]
        """
        return self._ip_domain_list

    @ip_domain_list.setter
    def ip_domain_list(self, ip_domain_list):
        """Sets the ip_domain_list of this BsfInfo.


        :param ip_domain_list: The ip_domain_list of this BsfInfo.  # noqa: E501
        :type: list[str]
        """

        self._ip_domain_list = ip_domain_list

    @property
    def ipv4_address_ranges(self):
        """Gets the ipv4_address_ranges of this BsfInfo.  # noqa: E501


        :return: The ipv4_address_ranges of this BsfInfo.  # noqa: E501
        :rtype: list[Ipv4AddressRange]
        """
        return self._ipv4_address_ranges

    @ipv4_address_ranges.setter
    def ipv4_address_ranges(self, ipv4_address_ranges):
        """Sets the ipv4_address_ranges of this BsfInfo.


        :param ipv4_address_ranges: The ipv4_address_ranges of this BsfInfo.  # noqa: E501
        :type: list[Ipv4AddressRange]
        """

        self._ipv4_address_ranges = ipv4_address_ranges

    @property
    def ipv6_prefix_ranges(self):
        """Gets the ipv6_prefix_ranges of this BsfInfo.  # noqa: E501


        :return: The ipv6_prefix_ranges of this BsfInfo.  # noqa: E501
        :rtype: list[Ipv6PrefixRange]
        """
        return self._ipv6_prefix_ranges

    @ipv6_prefix_ranges.setter
    def ipv6_prefix_ranges(self, ipv6_prefix_ranges):
        """Sets the ipv6_prefix_ranges of this BsfInfo.


        :param ipv6_prefix_ranges: The ipv6_prefix_ranges of this BsfInfo.  # noqa: E501
        :type: list[Ipv6PrefixRange]
        """

        self._ipv6_prefix_ranges = ipv6_prefix_ranges

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BsfInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BsfInfo):
            return True

        return self.to_dict() != other.to_dict()
