# coding: utf-8

"""
    NRF NFDiscovery Service

    NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0.alpha-4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class NFServiceVersion(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'api_version_in_uri': 'str',
        'api_full_version': 'str',
        'expiry': 'datetime'
    }

    attribute_map = {
        'api_version_in_uri': 'apiVersionInUri',
        'api_full_version': 'apiFullVersion',
        'expiry': 'expiry'
    }

    def __init__(self, api_version_in_uri=None, api_full_version=None, expiry=None, local_vars_configuration=None):  # noqa: E501
        """NFServiceVersion - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._api_version_in_uri = None
        self._api_full_version = None
        self._expiry = None
        self.discriminator = None

        self.api_version_in_uri = api_version_in_uri
        self.api_full_version = api_full_version
        if expiry is not None:
            self.expiry = expiry

    @property
    def api_version_in_uri(self):
        """Gets the api_version_in_uri of this NFServiceVersion.  # noqa: E501


        :return: The api_version_in_uri of this NFServiceVersion.  # noqa: E501
        :rtype: str
        """
        return self._api_version_in_uri

    @api_version_in_uri.setter
    def api_version_in_uri(self, api_version_in_uri):
        """Sets the api_version_in_uri of this NFServiceVersion.


        :param api_version_in_uri: The api_version_in_uri of this NFServiceVersion.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and api_version_in_uri is None:  # noqa: E501
            raise ValueError("Invalid value for `api_version_in_uri`, must not be `None`")  # noqa: E501

        self._api_version_in_uri = api_version_in_uri

    @property
    def api_full_version(self):
        """Gets the api_full_version of this NFServiceVersion.  # noqa: E501


        :return: The api_full_version of this NFServiceVersion.  # noqa: E501
        :rtype: str
        """
        return self._api_full_version

    @api_full_version.setter
    def api_full_version(self, api_full_version):
        """Sets the api_full_version of this NFServiceVersion.


        :param api_full_version: The api_full_version of this NFServiceVersion.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and api_full_version is None:  # noqa: E501
            raise ValueError("Invalid value for `api_full_version`, must not be `None`")  # noqa: E501

        self._api_full_version = api_full_version

    @property
    def expiry(self):
        """Gets the expiry of this NFServiceVersion.  # noqa: E501


        :return: The expiry of this NFServiceVersion.  # noqa: E501
        :rtype: datetime
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry):
        """Sets the expiry of this NFServiceVersion.


        :param expiry: The expiry of this NFServiceVersion.  # noqa: E501
        :type: datetime
        """

        self._expiry = expiry

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NFServiceVersion):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NFServiceVersion):
            return True

        return self.to_dict() != other.to_dict()
