# coding: utf-8

"""
    NRF NFDiscovery Service

    NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.   # noqa: E501

    The version of the OpenAPI document: 1.1.0.alpha-4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class VendorSpecificFeature(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'feature_name': 'str',
        'feature_version': 'str'
    }

    attribute_map = {
        'feature_name': 'featureName',
        'feature_version': 'featureVersion'
    }

    def __init__(self, feature_name=None, feature_version=None, local_vars_configuration=None):  # noqa: E501
        """VendorSpecificFeature - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._feature_name = None
        self._feature_version = None
        self.discriminator = None

        self.feature_name = feature_name
        self.feature_version = feature_version

    @property
    def feature_name(self):
        """Gets the feature_name of this VendorSpecificFeature.  # noqa: E501


        :return: The feature_name of this VendorSpecificFeature.  # noqa: E501
        :rtype: str
        """
        return self._feature_name

    @feature_name.setter
    def feature_name(self, feature_name):
        """Sets the feature_name of this VendorSpecificFeature.


        :param feature_name: The feature_name of this VendorSpecificFeature.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and feature_name is None:  # noqa: E501
            raise ValueError("Invalid value for `feature_name`, must not be `None`")  # noqa: E501

        self._feature_name = feature_name

    @property
    def feature_version(self):
        """Gets the feature_version of this VendorSpecificFeature.  # noqa: E501


        :return: The feature_version of this VendorSpecificFeature.  # noqa: E501
        :rtype: str
        """
        return self._feature_version

    @feature_version.setter
    def feature_version(self, feature_version):
        """Sets the feature_version of this VendorSpecificFeature.


        :param feature_version: The feature_version of this VendorSpecificFeature.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and feature_version is None:  # noqa: E501
            raise ValueError("Invalid value for `feature_version`, must not be `None`")  # noqa: E501

        self._feature_version = feature_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VendorSpecificFeature):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VendorSpecificFeature):
            return True

        return self.to_dict() != other.to_dict()
